### ISSUE TITLE
Can "--namespace" key be ignored for existing services?

### ISSUE THREAD

**Issue by Vest** [cloudfoundry-incubator/multiapps-cli-plugin#119]
Hi,

I am using the plugin: `cf deploy`, however my mta.yaml file has the service definition as "org.cloudfoundry.existing-service":

```
  - name: my_workflow
    type: org.cloudfoundry.existing-service
    parameters:
      service-name: my_workflow_service
      service: workflow
      service-plan: standard
```

When I deploy the mtar file using the command below, I get an error:

```
> cf deploy mta_archives\my.mtar --namespace com.test

Creating application "com.test-my_approuter" from MTA module "my_approuter"...
Error creating or updating application "com.test-my_approuter":
    Could not bind application "com.test-my_approuter" to service "com.test.my_workflow_service":
        404 Not Found: Service instance com.test.my_workflow_service not found.  <-- HERE!!!!!!
Proceeding with automatic retry... (3 of 3 attempts left)
```

Is it possible to ignore the namespace for a particular service? At least for the existing one? Otherwise, this feature "namespace" seems useless to me.

Thanks

**Comment by ddonchev** [comment]
Hi @Vest,
You can achieve this behavior with a parameter at the resource which you don't want to be affected
```yaml
- name: my_workflow
  parameters:
    apply-namespace: false
    ...
```
For more details you can check out this example: https://github.com/SAP-samples/cf-mta-examples/tree/master/namespace 
with the parameter usage in particular: https://github.com/SAP-samples/cf-mta-examples/blob/128987fc2601d193e30362ac86bca09d564a1ea3/namespace/module-and-service-with-apply-flag/mtad.yaml#L22

**Comment by Vest** [comment]
@ddonchev thank you for the reply.
Would it be possible to add this parameter to any SAP documentation? E.g. here - [The MTA Deployment Descriptor](https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.05/en-US/33548a721e6548688605049792d55295.html)? I have spent a lot of time in Google, and even with your help, there are only two results on Github:
![Is this really a documentaion?????](https://user-images.githubusercontent.com/1671049/96112804-7d733780-0ee3-11eb-9d1a-c35174ecdd20.png)

**Comment by ddonchev** [comment]
The parameter will been included in this page with a note that the feature is still not finalized and may be subject to change: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/9e34487b1a8643fb9a93ae6c4894f015.html 
The user assistance colleagues will be notified to update it.
