### ISSUE TITLE
[Question] CLI option to abort the ongoing process

### ISSUE THREAD

**Issue by meakgoz** [cloudfoundry-incubator/multiapps-cli-plugin#137]
### Description
If there was a deployment failed before, the plugin promtps a question;
`There is an ongoing operation for multi-target app <appname>. Do you want to abort it? (y/n)>`
What is the flag to suppress this prompt and abort automatically?

If there is a flag already, then it would be very nice to add this to the usage section in the README file.
If there is no flag, then can we request it as a feature?

Best, 
Emin.

**Comment by theghost5800** [comment]
Hi @meakgoz ,
There exists such flag `-f` already. With this flag specified, this won't require any interactive actions from your side. You can list all command line options of every command via `cf deploy --help` and you can take a look at command line documentation here - https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/65ddb1b51a0642148c6b468a759a8a2e.html#loio65ddb1b51a0642148c6b468a759a8a2e__section_irt_3dc_zs
