### ISSUE TITLE
"'deploy my.mtar' is not a registered command" on MacOS

### ISSUE THREAD

**Issue by eguo** [cloudfoundry-incubator/multiapps-cli-plugin#139]
### Description

Command $ cf deploy my.mtar -e my.mtaext on MacOS is returning following message

'deploy my.mtar' is not a registered command. See 'cf help -a'

### Your environment
*	MultiApps CF CLI Plugin version - 2.6.2
*	which CF vendor is used - SAP

### Steps to reproduce
Tell us how to reproduce this issue.
run command: $ cf deploy my.mtar -e my.mtaext

**Comment by theghost5800** [comment]
Hi @eguo ,
How did you install multiapps plugin? Did you use `cf install-plugin` command? Please share your output from execution of `cf plugins` command.
