### ISSUE TITLE
invalid memory address or nil pointer dereference when deploying using *.mtar as the filename 

### ISSUE THREAD

**Issue by longieirl** [cloudfoundry-incubator/multiapps-cli-plugin#140]
### Description
Looking to streamline the commands generated in our application so that there is only every one *.mtar produced and deployed. This will allow our application to work with other yeoman generators which produce mtar archives with a different naming convention.

The commands work fine on SBAS and on latest Mac Big Sur but fail on windows 10 machines as the wildcard i.e. `*.mtar` is not being expanded into a full filename.

### Your environment
*	MultiApps CF CLI Plugin version - 2.6.2 / cf6(6.53.0+8e2b70a4a.2020-10-01)  / cf7( 7.2.0+be4a5ce2b.2020-12-10)
*	which CF vendor is used - cf installed following these [instructions](https://github.com/cloudfoundry/cli/blob/master/doc/installation-instructions/installation-instructions-v6.md#installers-and-compressed-binaries)
*      OS - Mac/Windows/SBAS

<img width="843" alt="Screenshot 2021-06-28 at 10 30 04" src="https://user-images.githubusercontent.com/4520960/123614528-56079500-d7fc-11eb-9553-abf5e8d679d0.png">

### Steps to reproduce
Our application is using the following npm command on Windows 10 machine;

```
"deploy": "cf deploy mta_archives/*.mtar"
```

Issue is experienced for both cf6 and cf7

### Additional information

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x1195638]

goroutine 1 [running]:
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.getMtaArchive(0xc00004ad20, 0x1, 0x1, 0x101, 0xc000017208, 0xc0004ff4d0, 0xe93076, 0xc00007ef00)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/deploy_command.go:354 +0x218
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.(*DeployCommand).executeInternal(0xc00059c700, 0xc00004ad20, 0x1, 0x1, 0xc000498270, 0x2b, 0xc00029eba0, 0xc000499ce0, 0x24, 0xc00068e940, ...)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/deploy_command.go:183 +0x290
github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands.(*BaseCommand).Execute(0xc00051e3f0, 0xc0000280b0, 0x1, 0x1, 0x0)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/commands/base_command.go:132 +0x5b5
main.(*MultiappsPlugin).Run(0x16d8ad0, 0x13524c0, 0xc00050fb00, 0xc0000280a0, 0x2, 0x2)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/multiapps_plugin.go:45 +0x1c2
github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/cloudfoundry/cli/plugin.Start(0x1346340, 0x16d8ad0)
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/vendor/github.com/cloudfoundry/cli/plugin/plugin_shim.go:30 +0x1eb
main.main()
        /root/go/src/github.com/cloudfoundry-incubator/multiapps-cli-plugin/multiapps_plugin.go:65 +0x45
```

**Comment by longieirl** [comment]
Hi,
Just wondering if there is any response to this issue?

Thanks.
John

**Comment by theStiggySpd** [comment]
Hello,
Any update here please?

Regards,
Sushant

**Comment by IvanBorislavovDimitrov** [comment]
Hello,

Asterisk symbol is not supported by the multiapps cli plugin and respectively not handled well at all. If you execute "cf deploy *.mtar" the command will fail the same way, so I would recommend letting bash resolve the "*".
You can try something similar in your package.json:
package.json:
{
  "scripts": {
    "deploy": "bash -c 'cf deploy *.mtar -f'"
  }
}
npm run-script deploy

This way the asterisk symbol will be resolved to the mtar's name in the current directory and then passed to the deploy command.

Best regards,
Ivan

**Comment by longieirl** [comment]
Hi,
Thank you for responding; Yes that will work but expecting a user to configure and setup bash if not already installed is not a great user experience! We'll need to realign the behaviour to support different OS's.
Thanks.
John

**Comment by ianquigley-sap** [comment]
Hi there,
Can we please reopen this issue?  It is still an issue on Windows. Is there an intention to support wildcard in the filename on windows?
Thanks,
Ian

**Comment by quiggs1001** [comment]
Any update on this?  Can this be re-opened or at least detailed why it doesn't work on Windows, but does on Mac/Linux?  Expecting our windows users to install Bash to accommodate the suggested fix is not a good user experience.
