### ISSUE TITLE
CF CLI Plugin -u option if no default multiapps-controller exists

### ISSUE THREAD

**Issue by VaskoBozhurski** [cloudfoundry-incubator/multiapps-cli-plugin#43]
### Description
The `-u` option to specify a custom multiapps-controller url does not work if there is no multiapps-controller on any of the default routes expected by the CF CLI plugin. This is only an issue if the `DEPLOY_SERVICE_URL` env is not set.

### Expected behavior
`-u` should work regardless of the existence of a default route multiapps-controller on the CF instance. To do so, the `-u` functionality should be triggered before the check for the default multiapps-controller URLs.

### Internal Tracking Number:
LMCROSSITXSADEPLOY-1216

**Comment by ddonchev** [comment]
fixed
