### ISSUE TITLE
BG deployment is not successful

### ISSUE THREAD

**Issue by erezu2** [cloudfoundry-incubator/multiapps-cli-plugin#46]
### Description
Hi all,

In my space, I have an application named "portal-cf-technical-support"

I am doing BG deployment with Piper step in order to deploy a newer version of it by:
                                    deployToCloudFoundry( script: this, deployTool: 'mtaDeployPlugin', deployType: blue-green, mtaDeployParameters: '-f', cfApiEndpoint: api, cfOrg: org, cfSpace: space, cfCredentialsId: deployUser, mtaPath: pathToFile, mtaExtensionDescriptor: 'mta.mtaext')

after deployment is done, i see 2 versions of the application.
the original one named "portal-cf-technical-support" and another one named "portal-cf-technical-support-green" with almost same url but with postfix "idle"
I would expect that after deployment is done, i would have only the new version deployed with the original name.

### Your environment
Listing installed plugins...

plugin              version   command name                 command help
blue-green-deploy   1.3.0     blue-green-deploy, bgd       Zero-downtime deploys with smoke tests
MtaPlugin           2.0.0     bg-deploy                    Deploy a multi-target app using blue-green deployment
MtaPlugin           2.0.0     deploy                       Deploy a new multi-target app or sync changes to an existing one
MtaPlugin           2.0.0     download-mta-op-logs, dmol   Download logs of multi-target app operation
MtaPlugin           2.0.0     mta                          Display health and status for a multi-target app
MtaPlugin           2.0.0     mta-ops                      List multi-target app operations
MtaPlugin           2.0.0     mtas                         List all multi-target apps
MtaPlugin           2.0.0     purge-mta-config             Purge no longer valid configuration entries
MtaPlugin           2.0.0     undeploy                     Undeploy a multi-target app

### Steps to reproduce
In jenkins job login to your cf space, clone the mtar application and use Piper:
deployToCloudFoundry( script: this, deployTool: 'mtaDeployPlugin', deployType: blue-green, mtaDeployParameters: '-f', cfApiEndpoint: api, cfOrg: org, cfSpace: space, cfCredentialsId: deployUser, mtaPath: pathToFile, mtaExtensionDescriptor: 'mta.mtaext')
### Additional information
This is the console output:
[deployToCloudFoundry] Deploying MTA (target/portal-cf-technical-support.mtar) with following parameters: -e mta-prod.mtaext -f
[Pipeline] sh
[GRADLE-DEPLOY-portal-cf-technical-support-i066861-gradle-dsl] Running shell script
API endpoint: https://api.cf.sap.hana.ondemand.com
Authenticating...
OK

Targeted org SAP_PORTAL_SERVICES

Targeted space val

API endpoint:   https://api.cf.sap.hana.ondemand.com (API version: 2.120.0)
User:           ****
Org:            SAP_PORTAL_SERVICES
Space:          val
Listing installed plugins...

plugin              version   command name                 command help
blue-green-deploy   1.3.0     blue-green-deploy, bgd       Zero-downtime deploys with smoke tests
MtaPlugin           2.0.0     bg-deploy                    Deploy a multi-target app using blue-green deployment
MtaPlugin           2.0.0     deploy                       Deploy a new multi-target app or sync changes to an existing one
MtaPlugin           2.0.0     download-mta-op-logs, dmol   Download logs of multi-target app operation
MtaPlugin           2.0.0     mta                          Display health and status for a multi-target app
MtaPlugin           2.0.0     mta-ops                      List multi-target app operations
MtaPlugin           2.0.0     mtas                         List all multi-target apps
MtaPlugin           2.0.0     purge-mta-config             Purge no longer valid configuration entries
MtaPlugin           2.0.0     undeploy                     Undeploy a multi-target app

Use 'cf repo-plugins' to list plugins in registered repos available to install.
Deploying multi-target app archive target/portal-cf-technical-support.mtar in org SAP_PORTAL_SERVICES / space val as ****...
Aborting multi-target app operation with id 426415992...
OK
Uploading 1 files...
  /home/jenkins/workspace/deployServiceJobs-i066861-gradle-dsl/GRADLE-DEPLOY-portal-cf-technical-support-i066861-gradle-dsl/target/portal-cf-technical-support.mtar
OK
Uploading 1 files...
  /home/jenkins/workspace/deployServiceJobs-i066861-gradle-dsl/GRADLE-DEPLOY-portal-cf-technical-support-i066861-gradle-dsl/mta-prod.mtaext
OK
Starting deployment process...
OK
Monitoring process 427998041...
  Validating parameters...
  Processing MTA archive...
  Processing MTA extension descriptors...
  Detecting MTA major schema version...
  MTA schema version: 3.1.0
  Detecting deploy target...
  Detected deploy target "SAP_PORTAL_SERVICES val"
  Validating and merging descriptors...
  Detecting deployed MTA...
  No deployed MTA detected
  Collecting system parameters...
  New MTA version: 2.10.0-20181003140145+b39ccc1495f2101159987b982aa0693b6252459c
  Building cloud deployment model...
  Building cloud undeployment model...
  Validating services to create...
  Validating applications to deploy...
  Deleting unused reserved routes...
  Creating or updating services...
  Preparing applications deployment...
  Building cloud deployment model for application "portal-cf-technical-support"...
  Checking application "portal-cf-technical-support"...
  Application "portal-cf-technical-support" does not exist
  Creating application "portal-cf-technical-support"...
  Uploading application "portal-cf-technical-support"...
  Matched files count: 112
  Matched resources processed, total size is 9,943,750
  Upload status: queued
  Upload status: running
  Upload status: running
  Upload status: running
  Upload status: running
  Application "portal-cf-technical-support" uploaded
  Scaling application "portal-cf-technical-support"...
  Upload status: finished
  Starting application "portal-cf-technical-support"...
  Application "portal-cf-technical-support" staged
  1 of 1 instances running (1 running)
  Application "portal-cf-technical-support" started and available at "https://portal-cf-technical-support-val.cfapps.sap.hana.ondemand.com"
  Publishing public provided dependencies for application "portal-cf-technical-support"...
  Building cloud deployment model for application "portal-cf-health-check"...
  Checking application "portal-cf-health-check"...
  Application "portal-cf-health-check" does not exist
  Creating application "portal-cf-health-check"...
  Uploading application "portal-cf-health-check"...
  Matched files count: 106
  Matched resources processed, total size is 7,653,833
  Upload status: queued
  Upload status: running
  Upload status: running
  Upload status: running
  Upload status: running
  Application "portal-cf-health-check" uploaded
  Scaling application "portal-cf-health-check"...
  Upload status: finished
  Starting application "portal-cf-health-check"...
  Application "portal-cf-health-check" staged
  1 of 1 instances running (1 running)
  Application "portal-cf-health-check" started and available at "https://portal-cf-health-check-val.cfapps.sap.hana.ondemand.com"
  Publishing public provided dependencies for application "portal-cf-health-check"...
  Building cloud deployment model for application "portal-cf-technical-support-ar"...
  Checking application "portal-cf-technical-support-ar"...
  Application "portal-cf-technical-support-ar" does not exist
  Creating application "portal-cf-technical-support-ar"...
  Uploading application "portal-cf-technical-support-ar"...
  Matched files count: 116
  Matched resources processed, total size is 12,826,544
  Upload status: queued
  Upload status: running
  Upload status: running
  Upload status: running
  Upload status: running
  Upload status: finished
  Application "portal-cf-technical-support-ar" uploaded
  Scaling application "portal-cf-technical-support-ar"...
  Starting application "portal-cf-technical-support-ar"...
  Application "portal-cf-technical-support-ar" staged
  0 of 1 instances running (1 starting)
  1 of 1 instances running (1 running)
  Application "portal-cf-technical-support-ar" started and available at "https://portal-cf-technical-support-ar-val.cfapps.sap.hana.ondemand.com"
  Publishing public provided dependencies for application "portal-cf-technical-support-ar"...
  Creating subscriptions...
  Registering service URLs...
  Deleting discontinued subscriptions...
  Deleting discontinued published dependencies...
  Unregistering discontinued service URLs...
  Creating service brokers...
  Updating subscribers...
Process finished.
Use "cf dmol -i 427998041" to download the logs of the process.

**Comment by ddonchev** [comment]
Hello and thanks for being patient with the response. 
The given output seems to be of a 'cf deploy ...' process which explains the version having no '-color' or '-idle' suffix to the app-name/route. The other version is created via a 'cf bg-deploy' execution. During the first phase of the bg-deployment (before the switch to a new version) a new version of the mta is spun-up on temporary (-idle) routes. You seem to have seen that state of your space.
The blue-green deploy process continues with mapping the 'live' routes new (-color) apps, the old apps get deleted as well as the '*-idle' routes. 

Indeed, after a successfully bg-deploy process, there should be only one version of the app in the space. It should have a color suffix (e.g. -blue) and should have normal routes (not having -idle suffix). 

Most probably in the current case the blue-green deployment was ongoing or has stopped due to an error before reaching the 'switch'.
