### ISSUE TITLE
Unable to install the plugin on a windows machine

### ISSUE THREAD

**Issue by salahchakchouki** [cloudfoundry-incubator/multiapps-cli-plugin#51]
### Description
Failed to install mta_plugin_windows_amd64.exe

### Your environment
*	MultiApps CF CLI Plugin version - v2.0.8
*	which CF vendor is used - SAP

### Steps to reproduce
1. Downloaded the plugin from https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/download/v2.0.8/mta_plugin_windows_amd64.exe
2.  ran the below command

D:\cf>cf install-plugin d:\mta_plugin_windows_amd64.exe -f
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
dial tcp 127.0.0.1:53128: socket: An invalid argument was supplied.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED

**Comment by ddonchev** [comment]
Hi, and thanks for being patient with this response.
To avoid such mishaps, the cf community repo can now be utilized to install & update the multiapps plugin. e.g.
> cf install-plugin multiapps -f 
This will make the cf cli find, download and install (or update) the latest released version. 
Please reopen if this is not an applicable solution for the current case.
