### ISSUE TITLE
Automatically download mta op logs after deployment

### ISSUE THREAD

**Issue by LukasHeimann** [cloudfoundry-incubator/multiapps-cli-plugin#68]
### Description

After running a deployment, a message is displayed with information on how to download the mta op logs, i.e. `mta dmol -i 12345`. When I run a deployment on a CI server, I usually want to download the logs after deployment - especially if something goes wrong. However, parsing the logs of `cf deploy` to get the `operation_id` is hard.¹ Manually downloading the logs with my personal user does not seem to work (the CI server uses a technical user for deployment).

### Expected Behavior

When running `cf deploy` (or `bg-deploy`), I want to be able to pass a flag to automatically download the logs after the deployment is finished. The flag could look like this:

```
cf deploy my.mta --download-mta-op-logs ON_FAILURE
cf deploy my.mta --download-mta-op-logs ALWAYS
```

This way, manually fiddling around with the `operation_id` would not be necessary anymore in both CI and manual deployment scenarios.

The parameter `-d` of `cf dmol` to specify the directory to store the logs to is not used by `cf deploy`, so it could be used there as well.

Thank you for considering this enhancement!

---
¹ Especially, if you use the excellent [SAP jenkins-library](https://github.com/SAP/jenkins-library), where getting the `stdout` would require quite some refactoring ([source](https://github.com/SAP/jenkins-library/blob/master/vars/cloudFoundryDeploy.groovy#L322)), as you can't use `returnStdout` and `returnStatus` at the same time.

**Comment by ddonchev** [comment]
For handling this and similar scenario, the ui of the 'cf dmol' command will be extended to accept an MTA ID. E.g. 'cf dmol my.mta.id'. This would result in downloading of the logs of the last process for that mta (having that id). 
Pros: More flexible and easy to script after a deploy command in different cases (on success/error/always); Feature does not get buried in ui of deploy/bg-deploy command; Feature will improve the usability of the cf dmol command (no need of process-id for most cases).

**Comment by ddonchev** [comment]
tracked in team backlog: LMCROSSITXSADEPLOY-1578
