### ISSUE TITLE
Unable to install multiapps plugin thanks to CLI on a windows machine

### ISSUE THREAD

**Issue by YannDeriat** [cloudfoundry-incubator/multiapps-cli-plugin#72]
### Description
Failed (i/o timeout error) during plugin "multiapps-plugin.win64" installation

### Steps to reproduce
1) Try to download multiapps plugin from this URL : 
https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/tag/v2.1.1/multiapps-plugin.win64

2)I ran the command below :
V:\>cf install-plugin multiapps -f
Searching CF-Community for plugin multiapps...
Plugin multiapps 2.1.1 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Starting download of plugin binary from repository CF-Community...
Get https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/releases/download/v2.1.1/multiapps-plugin.win64: dial tcp 140.82.118.3:443: i/o timeout
FAILED

Thanks in advance for your support.

Kind Regards

**Comment by valentinEmpy** [comment]
Hello @YannDeriat ,

As the issue is quite old and the github issues section has been inactive until now - it was not our main issues channel, I do have to ask - is this still relevant?
Are you able to consistently reproduce it?
It seems more like a connectivity issue than an issue associated with the plugin, however.

**Comment by killerfurbel** [comment]
Having the same problem. Tried as administrator, but doesn't help.

```
PS C:\> cf install-plugin multiapps
Searching CF-Community for plugin multiapps...
Plugin multiapps 2.2.0 found in: CF-Community
Attention: Plugins are binaries written by potentially untrusted authors.
Install and use plugins at your own risk.
Do you want to install the plugin multiapps? [yN]: y
Starting download of plugin binary from repository CF-Community...
 14.22 MiB / 14.22 MiB [===================================================================================] 100.00% 2s
dial tcp 127.0.0.1:54663: socket: Ein ungültiges Argument wurde angegeben.
exit status 1
File is not a valid cf CLI plugin binary.
FAILED
```

the port number is different each time I run the command.

there was something similar with another plugin: https://github.com/pivotal-cf/pcfdev/issues/210#issuecomment-383196510

**Comment by theghost5800** [comment]
@killerfurbel Do you use some proxy settings in your environment? If yes then try to unset proxy settings in your console. You can find more information about proxy settings for CF CLI [here](https://docs.cloudfoundry.org/cf-cli/http-proxy.html#windows)

**Comment by killerfurbel** [comment]
I'm not using any proxy. The plugin download finishes without any problems. @YannDeriat explicitly mentioned "windows machine", so I just tried in wsl and it just works.

I also tried downloading the plugin manually and installing it via `cf install-plugin .\multiapps-plugin.win64` on windows, but it results in the same error message...

**Comment by theghost5800** [comment]
@killerfurbel Sorry for late response but I can't reproduce this issue on my machine (Windows 10 64-bit). I found the same [issue](https://github.com/cloudfoundry/cli/issues/1184) reported to cf cli for another installation of plugin. It is possible to be related with Windows Firewall rules. You can try to disable your firewall and run `cf install-plugin multiapps`
