### ISSUE TITLE
How to decrease deployment duration for complex MTA project

### ISSUE THREAD

**Issue by AndreasMueller-SAP** [cloudfoundry-incubator/multiapps-cli-plugin#74]
### Description
We are using the plugin to deploy an MTA project containing a bunch of services and applications to Cloud Foundry. The deployment of our MTA project takes up to 30 minutes and we would like to know how we could decrease the deployment time. In the following an example mta.yaml which visualizes the complexity of our project.

    _schema-version: "3.1"
    ID: local.example
    version: 0.0.6
    description: An example MTA project
    
    modules:
      - name: my-db
        type: nodejs
        path: db
        parameters:
          memory: 256M
          disk-quota: 256M
          routes:
          - route: db${url-delimiter}${app-url}.${domain}
        requires:
          - name: my-hdi-container
          - name: hdi-credentials
            properties:
              hdi_dynamic_deploy_user: ~{user}
              hdi_dynamic_deploy_password: ~{password}
        provides:
          - name: dynamic_db_deployment
            properties:
              url: ${protocol}://db${url-delimiter}${app-url}.${domain}
              user: ${generated-user}
              password: ${generated-password}
    
      - name: my-root
        type: java
        path: backend
        build-parameters:
          # disable adding this module into the mta archive for any target platform
          supported-platforms: []
          builder: maven
          maven-opts:
            command: ["clean", "install"]
          build-result: "**/target/*.war"
          timeout: 15m
    
      - name: my-frontend-api
        type: java
        path: backend/frontend-api
        parameters:
          memory: 1024M
          disk-quota: 256M
          routes:
            - route: frontend-api${url-delimiter}${app-url}.${domain}
        provides:
          - name: frontend-api
            properties:
              url: ${protocol}://frontend-api${url-delimiter}${app-url}.${domain}
        properties:
          TENANT_HOST_PATTERN: ${protocol}://%s${url-delimiter}${app-url}.${domain}
    
        build-parameters:
          builder: fetcher
          fetcher-opts:
            repo-type: maven
            repo-coordinates: "local.example:frontend-api:1.0-SNAPSHOT:war"
          requires:
            - name: my-root
        requires:
          - name: my-hdi-container
            properties:
              JBP_CONFIG_RESOURCE_CONFIGURATION: >-
                [tomcat/webapps/ROOT/META-INF/context.xml:
                {"service_name_for_DefaultDB" : "~{hdi-container-name}"}]
          - name: feature-flags
          - name: hdi-credentials
            properties:
              dynamic_db_deployment_user: ~{user}
              dynamic_db_deployment_password: ~{password}
          - name: dynamic_db_deployment
            properties:
              dynamic_db_deployment_url: ~{url}
              TENANT_DB_DEPLOY_URL: ~{url}
              TENANT_DB_DEPLOY_USER: ~{user}
              TENANT_DB_DEPLOY_PASSWORD: ~{password}
    
          - name: my-uaa
          - name: saas-registry
          - name: my-destination
    
      - name: my-partner-api
        type: java
        path: backend/partner-api
        parameters:
          memory: 1024M
          disk-quota: 256M
          routes:
          - route: partner-api${url-delimiter}${app-url}.${domain}
        provides:
          - name: partner-api
            properties:
              url: ${protocol}://partner-api${url-delimiter}${app-url}.${domain}
        build-parameters:
          builder: fetcher
          fetcher-opts:
            repo-type: maven
            repo-coordinates: "local.example:partner-api:1.0-SNAPSHOT:war"
          requires:
              - name: my-root
        requires:
          - name: my-hdi-container
            properties:
              JBP_CONFIG_RESOURCE_CONFIGURATION: >-
                [tomcat/webapps/ROOT/META-INF/context.xml:
                {"service_name_for_DefaultDB" : "~{hdi-container-name}"}]
          - name: feature-flags
          - name: hdi-credentials
            properties:
              dynamic_db_deployment_user: ~{user}
              dynamic_db_deployment_password: ~{password}
          - name: dynamic_db_deployment
            properties:
              dynamic_db_deployment_url: ~{url}
              TENANT_DB_DEPLOY_URL: ~{url}
              TENANT_DB_DEPLOY_USER: ~{user}
              TENANT_DB_DEPLOY_PASSWORD: ~{password}
    
          - name: my-broker-uaa
    
      - name: my-app-router
        type: nodejs
        path: appRouter
        parameters:
          memory: 128M
          app-name: my-app-router
        properties:
          TENANT_HOST_PATTERN: ^(.*)${url-delimiter}${app-url}.${domain}
        build-parameters:
          requires:
            - name: my-vue
              artifacts: ["target/frontend/*"]
              target-path: "resources/my"
    
        requires:
          - name: frontend-api
            group: destinations
            properties:
              name: my-frontend-api
              url: ~{url}
              forwardAuthToken: true
          - name: partner-api
            group: destinations
            properties:
              name: my-partner-api
              url: ~{url}
              forwardAuthToken: true
          - name: my-uaa
          - name: my-xsahaa
            group: destinations
            properties:
              name: my-xsahaa
              url: ~{url}
              forwardAuthToken: true
    
      - name: my-vue
        type: html5
        path: app
        build-parameters:
          builder: npm
          # disable adding this module into the mta archive for any target platform
          supported-platforms: []
          timeout: 15m
    
      - name: my-api-broker
        type: nodejs
        path: broker
        requires:
          - name: my-broker-uaa
          - name: partner-api
        parameters:
          memory: 128M
          disk-quota: 256M
          routes:
          - route: api-broker${url-delimiter}${app-url}.${domain}
        build-parameters:
          builder: npm
      
      - name: my-xsahaa
        type: java
        requires:
          - name: my-uaa
          - name: my-hdi-container
    
        properties:
          TARGET_RUNTIME: tomee
          USE_NAMED_USER: true
          SECONDARY_ROUTING_PERCENT: 0
        provides:
          - name: my-xsahaa
            properties:
              url: ${protocol}://xsahaa${url-delimiter}${app-url}.${domain}
    
        parameters:
          memory: 1024M
          routes:
          - route: xsahaa${url-delimiter}${app-url}.${domain}
    
        build-parameters:
          builder: fetcher
          fetcher-opts:
            repo-type: maven
            repo-coordinates: com.sap.xsahaa:java-xsahaa:1.5.6:war
    
    resources:
      - name: my-hdi-container
        parameters:
          config:
            database_id: ${database-id}
        properties:
          hdi-container-name: "${service-name}"
        type: com.sap.xs.managed-hdi-container
    
      - name: my-uaa
        type: com.sap.xs.uaa-space
        parameters:
          path: security/xs-security.json
          service-plan: application
    
      - name: my-broker-uaa
        type: com.sap.xs.uaa-broker
        parameters:
          path: security/xs-broker-security.json
          service-plan: broker
    
      - name: my-destination
        type: destination
    
      - name: feature-flags
        type: org.cloudfoundry.managed-service
        parameters:
          service: feature-flags
          service-plan: standard
          path: feature-flags.json
    
      - name: hdi-credentials
        properties:
          user: ${generated-user}
          password: ${generated-password}
    
      - name: saas-registry
        type: org.cloudfoundry.managed-service
        parameters:
          service-plan: application
          service: saas-registry
          config:
            appId: ${xs-app-name}!t${provider-tenant-index}
            appName: ${xs-app-name}
            appUrls:
              onSubscription: https://frontend-api${url-delimiter}${app-url}.${default-domain}/callback/v1.0/tenants/{tenantId}
              getDependencies: https://frontend-api${url-delimiter}${app-url}.${default-domain}/callback/v1.0/dependencies
            displayName: ${saas-display-name}
            description: ${saas-description}
 
 I hope this example mta.yaml gives enough context.    

### Your environment
*	MultiApps CF CLI Plugin version - 2.1.1 
*	which CF vendor is used - SAP Cloud Platform
*	which backing services are used - SAP HANA

### Steps to reproduce

Setup a project as described by the example mta.yaml and deploy it to the SAP Cloud Platform.

**Comment by IObert** [comment]
I agree. A possible approach might be to parallelize the resource creation (I think this happens sequentially today) or to add a CLI option to re-deploy only single modules.

**Comment by AndreasMueller-SAP** [comment]
I as far as I know there is the possibility of partial deployments.

https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/issues/71#issuecomment-498988108

Is it possible for the MTA plugin to determine based on metadata of the available deployed modules which module needs to be updated. Is there a checksum available for each deployed module which could be used to determine changes?

**Comment by ddonchev** [comment]
Hi Andreas, Marus.

Currently, all services are processed in parallel so there is less room for optimisation there.

The biggest improvement to deploy times can be achieved by using parallel application (module) processing. This is activated with a global parameter in the deployment descriptor:
```yaml
_schema-version: 3.3.0
ID: hello-world
version: 1.0.0
parameters:
  enable-parallel-deployments: true
```
You can check out this example for details: https://github.com/SAP-samples/cf-mta-examples/tree/master/parallel-deployment

In addition we plan to also process app <-> service bindings in parallel in near future. ( https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/projects/1#card-31742204 )

Partial deployment is useful if you actually want to update only certain apps/services of your MTA and you already know which they are. Have in mind that all dependencies of the so selected parts of your MTA should be already available. More details in this example:  https://github.com/SAP-samples/cf-mta-examples/tree/master/partial-build-deploy 

Thanks for being patient with this reply :)
