### ISSUE TITLE
dmol does not create .log files

### ISSUE THREAD

**Issue by cuhland** [cloudfoundry-incubator/multiapps-cli-plugin#80]
### Description
Most of the IDEs & Text Editors have a syntax highlighting for log files.
It is a little bit annoying to add always the `.log` file extension to the downloaded log files after 
a `cf dmol -i 123`. 

### Your environment
*	MultiApps CF CLI Plugin version - 2.1.2
*	which CF vendor is used - SAP/SCP

### Steps to reproduce
After deployment the stdout is
```sh
Process finished.
Use "cf dmol -i 123" to download the logs of the process.
```
When downloading the logs the `MAIN_LOG` and all other log files do not have the log file suffix. 
It should be **`MAIN_LOG.log`**

**Comment by ddonchev** [comment]
Tracked in dev team backlog with item LMCROSSITXSADEPLOY-1780

**Comment by ddonchev** [comment]
Note: We plan this to be fixed on the back-end side of the service - the files will be downloaded with proper names, not renamed in the client.

**Comment by ddonchev** [comment]
Fixed and delivered in SCP
`cf dmol --mta anatz --last 1                                                                                                                                                                                                           Downloading logs of multi-target app operation with ID 55132f87-81ac-11ea-892b-eeee0a9b04de in org *** / space *** as dimitar.donchev@sap.com...
OK
Saving logs to ***/mta-op-55132f87-81ac-11ea-892b-eeee0a9b04de...
  OPERATION.log
  anatz-green.log
OK`
The files have been renamed: MAIN_LOG -> OPERATION.log ; The cf apps still get logs of their own, having the name of the app with the .log suffix.
