### ISSUE TITLE
Delete backend services in order of dependency.

### ISSUE THREAD

**Issue by DanieleStrafile** [cloudfoundry-incubator/multiapps-cli-plugin#96]
### Description
Hello everyone,

when you undeploy an application (and want to also eliminate its bound services) using cf undeploy --delete-services, the services seem to be deleted in arbitrary order and this leads to the process not working as expected, as some services have other dependencies on other services and the process is likely to fail because the deletion order is arbitrary. Is there a way to specify exactly in which order the services should be deleted?  many thanks

Additional question: 

### Your environment
*	MultiApps Controller version - 2.1.3
*	MultiApps CF CLI Plugin version - cf version 6.45.0+5f9ff16f9.2019-06-03
*	which CF vendor is used - SAP
*	which backing services are used - destination, html5-apps-repo, managed-hana, application-logs, portal, html5-apps-repo, saas-registry, xsuaa

### Steps to reproduce
Tell us how to reproduce this issue.
cf undeploy testapp --delete-services

**Comment by DanieleStrafile** [comment]
Question already answered by

Dimitar Donchev  7 minutes ago

Hi @Daniele Strafile, for now, the MTA descriptor defines services with no way to specify dependencies. As a result, creation/update always happen in parallel, and deletion order is not deterministic.
Recently a few scenarios raised the requirement to be able to define such dependencies, which would enable deterministic sequential creation/update and deletion. The item is in the team’s pipeline but most probably won’t be delivered within Q1 this year.  You can watch the status in this BI : https://sapjira.wdf.sap.corp/browse/LMCROSSITXSADEPLOY-1825 

Hence closing the issue. Thank you

**Comment by ddonchev** [comment]
The requirement is tracked in the OSS in the following board: https://github.com/cloudfoundry-incubator/multiapps-cli-plugin/projects/1#card-31736147
